CREATE TABLE IF NOT EXISTS users (
  id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
  dawn_id INTEGER DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS groups (
  id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
  user INTEGER REFERENCES users(id) NOT NULL,
  name TEXT NOT NULL,
  note TEXT DEFAULT NULL,
  theme TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
  user INTEGER REFERENCES users(id) NOT NULL,
  title TEXT NOT NULL,
  finished BOOLEAN NOT NULL DEFAULT false,
  created_at TEXT NOT NULL,
  due TEXT,
  repeat INTEGER DEFAULT NULL,
  in_group INTEGER REFERENCES groups(id) DEFAULT NULL,
  note TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  sid TEXT NOT NULL,
  expire TEXT NOT NULL,
  user INTEGER REFERENCES users(id)
);