CREATE TABLE IF NOT EXISTS users (
  id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
  dawn_id INTEGER DEFAULT NULL,
  update_token TEXT DEFAULT NULL,
  settings TEXT NOT NULL DEFAULT '{}'
);

-- CREATE TABLE IF NOT EXISTS user_tags (
-- name TEXT NOT NULL,
-- user_id INTEGER REFERENCES users(id) NOT NULL,
-- UNIQUE(name, user_id)
-- );
CREATE TABLE IF NOT EXISTS groups (
  id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
  user INTEGER REFERENCES users(id) NOT NULL,
  name TEXT NOT NULL,
  note TEXT DEFAULT NULL,
  theme TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
  user INTEGER REFERENCES users(id) NOT NULL,
  title TEXT NOT NULL,
  finished BOOLEAN NOT NULL DEFAULT false,
  created_at TEXT NOT NULL,
  due TEXT,
  repeat INTEGER DEFAULT NULL,
  in_group INTEGER REFERENCES groups(id) DEFAULT NULL,
  note TEXT DEFAULT NULL,
  tags TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS mood_entries (
  id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
  user INTEGER REFERENCES users(id) NOT NULL,
  emotion TEXT NOT NULL,
  note TEXT DEFAULT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  sid TEXT NOT NULL,
  expire TEXT NOT NULL,
  user INTEGER REFERENCES users(id)
);